module.exports = {
  DEDUP_START: "🔍 Start Deduplicatie scan...",
  DEDUP_OK: "✅ Deduplicatie succesvol afgerond.",
  DEDUP_SKIP: "⚠️ Dedup script niet gevonden of doelmap ontbreekt (skip)",
  AUDIT_START: "🛡️ Start Audit (phoenix-check)…",
  AUDIT_SUMMARY_FAIL: "❌ Fout: Functie show_summary niet geladen uit reports.sh",
  LOCK_STALE: "⚠️ Oude lock gevonden (>30 min). Opruimen en opnieuw starten…",
  LOCK_ACTIVE: "❌ Phoenix audit is al bezig.",
  CLEANUP_RUNNING: "Rapporten opschonen (behoud laatste 5)…",
  CLEANUP_DONE: "Systeem opgeschoond.",
  CLEANUP_FAIL: "Opschonen mislukt of map is leeg.",
  STEP_START: (n) => `--- ${n} ---`,
  STEP_SKIP: (cmd) => `[DRY-RUN] Overslaan: ${cmd}`,
  STEP_FAIL: (n) => `Fout tijdens ${n}`,
  GUARD_CHECK: "🐕 Guard Dog: Checking file sizes...",
  GUARD_PASS: (file, size) => `✅ PASS: ${file} (${size} KB)`,
  GUARD_FAIL: (file, size, max) => `❌ FAIL: ${file} is te groot (${size} KB). Limiet is ${max} KB.`,
  GUARD_CRITICAL: "🚨 COMMIT AFGEKEURD: Los de bloating op voordat je commit.",
  GUARD_SAFE: "�� Alles veilig: geen verdachte wijzigingen gevonden.",
  PRESET_CHECK: "🧪 Controleren van Babel presets...",
  ERR_BABEL_PRESET: "❌ CRITICAl: 'metro-react-native-babel-preset' ontbreekt in package.json!",
  REMEDY_BABEL: "💡 Actie: npm i -D metro-react-native-babel-preset",
  GIT_ADD: "• Git add",
  GIT_PUSH: "• Git push",
  GIT_COMMIT: (m) => `• Git commit: ${m}`,
  GIT_COMMIT_NONE: "⚠️ Nothing to commit",
  GIT_TAG: (t) => `• Create tag: ${t}`,
  COMMIT_DONE: (branch, tag) => `✅ Done. Branch: ${branch}, tag: ${tag}`,
  PHOENIX_FINAL_SMASH_STARTING: "PHOENIX_FINAL_SMASH_STARTING",
};
