const fs = require('fs');
const ts = require('typescript');
const { createBackup, ok, warn } = require('../utils');

function updateJsconfig(aliases, flags, filePath) {
  const newConfig = {
    "//": "AUTO-GENERATED by sync-aliases.js",
    "compilerOptions": { "baseUrl": ".", "paths": {} },
    "exclude": ["node_modules", "dist", "build", ".phoenix"]
  };

  aliases.forEach(a => {
    newConfig.compilerOptions.paths[`${a.name}/*`] = [`${a.target}/*`];
  });

  if (!flags.dryRun) {
    if (fs.existsSync(filePath)) createBackup(filePath);
    fs.writeFileSync(filePath, JSON.stringify(newConfig, null, 2), 'utf8');
    ok('JSConfig updated');
  }
}
module.exports = { updateJsconfig };
