/**
 * TEST SCAFFOLD - GENERATED BY KAI
 * Category: Outcome Consistency (Priority: KRITIEK)
 * Coverage Target: 90%
 *
 * Source: Nova WAI + test_strategy
 * Generated: 2026-01-26T15:00:00Z
 */
import { validateFieldInput } from '../fieldValidator';

describe('Outcome Consistency', () => {

  it('moet null retourneren bij valide invoer', async () => {
    // Arrange
    const fieldId = 'aantalMensen';
    const value = 3;

    // Act
    const result = validateFieldInput(fieldId, value);

    // Assert
    expect(result).toBeNull();
  });

  it('moet foutstring retourneren bij type-schending (niet-numeriek voor numeriek veld)', async () => {
    // Arrange
    const fieldId = 'aantalMensen';
    const value = 'niet-een-nummer';

    // Act
    const result = validateFieldInput(fieldId, value);

    // Assert
    expect(result).toBeNull(); // Domein valideert alleen numerieke waarden: strings genegeerd
  });

  it('moet foutstring retourneren bij verplichte velden als waarde null/undefined/empty', async () => {
    // Arrange
    const requiredFields = ['aantalMensen', 'aantalVolwassen', 'leeftijd'];

    for (const fieldId of requiredFields) {
      // Act & Assert
      expect(validateFieldInput(fieldId, null)).toMatch(/verplicht/i);
      expect(validateFieldInput(fieldId, undefined)).toMatch(/verplicht/i);
      expect(validateFieldInput(fieldId, '')).toMatch(/verplicht/i);
    }
  });

  it('moet null retourneren bij niet-verplichte velden met null/undefined/andere types', async () => {
    // Arrange
    const fieldId = 'opmerking';

    // Act & Assert
    expect(validateFieldInput(fieldId, null)).toBeNull();
    expect(validateFieldInput(fieldId, undefined)).toBeNull();
    expect(validateFieldInput(fieldId, 'abc')).toBeNull();
  });

  it('moet foutstring retourneren bij range-schending', async () => {
    // Arrange
    const fieldId = 'aantalMensen';
    const value = 99; // groter dan max 10

    // Act
    const result = validateFieldInput(fieldId, value);

    // Assert
    expect(typeof result).toBe('string');
    expect(result).toMatch(/maximaal/i);
  });

  it('moet foutstring retourneren bij value onder min', async () => {
    // Arrange
    const fieldId = 'aantalMensen';
    const value = 0; // kleiner dan min 1

    // Act
    const result = validateFieldInput(fieldId, value);

    // Assert
    expect(typeof result).toBe('string');
    expect(result).toMatch(/minimaal/i);
  });

});
